### ISSUE TITLE
parcel build: Property name expected type of string but got null

### ISSUE THREAD

**Issue by STLeee** [TooTallNate/proxy-agents#113]
### Environment details
**OS**: Windows 10
**Node.js**: v13.9.0
**npm**: 6.13.7
**https-proxy-agent**: 5.0.0

### Error message
```
×  ***\node_modules\https-proxy-agent\src\agent.ts: Property name expected type of 
string but got null
    at validate (C:\Users\a8365\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\@babel\types\lib\definitions\utils.js:160:13)
    at Object.validate (C:\Users\a8365\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\@babel\types\lib\definitions\utils.js:229:7)
    at validateField (C:\Users\a8365\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\@babel\types\lib\validators\validate.js:24:9)
    at validate (C:\Users\a8365\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\@babel\types\lib\validators\validate.js:17:3)
    at builder (C:\Users\a8365\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\@babel\types\lib\builders\builder.js:38:27)
    at Object.identifier (C:\Users\a8365\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\@babel\types\lib\builders\generated\index.js:340:31)
    at C:\Users\a8365\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\regenerator-transform\lib\hoist.js:32:29
    at Array.forEach (<anonymous>)
    at varDeclToExpr (C:\Users\a8365\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\regenerator-transform\lib\hoist.js:29:23)
    at exit (C:\Users\a8365\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\regenerator-transform\lib\hoist.js:51:20)
```

**Comment by TooTallNate** [comment]
This module has gone through a large refactor and modernization. I am closing this issue as a bit of house cleaning. If you feel that this issue still exists in the latest release, feel free to open a new issue.
