### ISSUE TITLE
BUG? Unhandled "socket hang up"  crashes node process (incl. async stacktrace)

### ISSUE THREAD

**Issue by 0xgeert** [TooTallNate/proxy-agents#26]
Using [longjohn](https://github.com/mattinsler/longjohn) I was able to get the async stacktrace of an unhandled "socket hang up" error which results in killing the node process. 

It's unhandled in that the error isn't exposed to the `superagent.end(function(err,res)`, and also not on `superagent.on("error", handleFN)`. 

Here's the longjohn stacktrace: 

```

Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1117:19)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
---------------------------------------------
    at fireErrorCallbacks (net.js:473:15)
    at TLSSocket.Socket._destroy (net.js:480:5)
    at TLSSocket.Socket.destroy (net.js:527:8)
    at TLSSocket.onHangUp (_tls_wrap.js:1119:14)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
---------------------------------------------
    at TLSSocket.Readable.on (_stream_readable.js:687:35)
    at TLSSocket.once (events.js:306:8)
    at Object.exports.connect (_tls_wrap.js:1122:10)
    at ondata (/Users/geert/sources/captured/pricing/node_modules/https-proxy-agent/https-proxy-agent.js:144:20)
    at Socket.read (/Users/geert/sources/captured/pricing/node_modules/https-proxy-agent/https-proxy-agent.js:82:12)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:186:7)
    at emitReadable_ (_stream_readable.js:432:10)
    at emitReadable (_stream_readable.js:426:7)
    at readableAddChunk (_stream_readable.js:187:13)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
---------------------------------------------
    at Socket.Readable.on (_stream_readable.js:687:35)
    at Socket.once (events.js:306:8)
    at read (/Users/geert/sources/captured/pricing/node_modules/https-proxy-agent/https-proxy-agent.js:83:17)
    at HttpsProxyAgent.connect [as callback] (/Users/geert/sources/captured/pricing/node_modules/https-proxy-agent/https-proxy-agent.js:187:5)
    at ProxyAgent.connect [as callback] (/Users/geert/sources/captured/pricing/node_modules/proxy-agent/index.js:147:9)
    at ProxyAgent.Agent.addRequest (/Users/geert/sources/captured/pricing/node_modules/agent-base/agent.js:81:8)
    at new ClientRequest (_http_client.js:212:16)
    at Object.request (http.js:26:10)
    at Object.request (https.js:206:15)
    at Object.request (/Users/geert/sources/captured/pricing/node_modules/agent-base/patch-core.js:52:20)
    at Request.request (/Users/geert/sources/captured/pricing/node_modules/superagent/lib/node/index.js:594:28)
    at Request.end (/Users/geert/sources/captured/pricing/node_modules/superagent/lib/node/index.js:750:8)
    at Promise (/Users/geert/sources/captured/pricing/src/drivers/driverMain.js:144:18)
    at Promise._execute (/Users/geert/sources/captured/pricing/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/geert/sources/captured/pricing/node_modules/bluebird/js/release/promise.js:483:18)
```

**Comment by XandeTorres** [comment]
Do you have solution how to propagate error to avoid silent crash?

**Comment by TooTallNate** [comment]
This module has gone through a large refactor and modernization. I am closing this issue as a bit of house cleaning. If you feel that this issue still exists in the latest release, feel free to open a new issue.
