### ISSUE TITLE
Uesrname and password for socks-proxy-agents

### ISSUE THREAD

**Issue by 1965514404** [TooTallNate/proxy-agents#307]
the older version use username and password with  
{
    hostname: '127.0.0.1',
    port: 10806,
    userId: '9DDFQFUODO',
    password: '7h88l87sojqed3'
}
on the newer version use it with error tell 

switch (url.protocol.replace(':', '')) {
                         ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at parseSocksURL (d:\2script\node\js\node_modules\socks-proxy-agent\dist\index.js:47:26)      
    at new SocksProxyAgent (d:\2script\node\js\node_modules\socks-proxy-agent\dist\index.js:93:35)
    at Object.<anonymous> (d:\2script\node\js\test1.js:130:20)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.18.0

**Comment by TooTallNate** [comment]
The API changed, you now need to pass a URL as the first argument to `new SocksProxyAgent()`. You specify the username/password in the URL:

```ts
new SocksProxyAgent('socks://username:password@example.com:9128');
```
