### ISSUE TITLE
Getting Error: write EPROTO 139876245374848:error:140770FC:SSL 

### ISSUE THREAD

**Issue by techyrajeev** [TooTallNate/proxy-agents#90]
Getting below error while trying to acess google authentication call from proxy server

```
server/node_modules/https-proxy-agent/node_modules/agent-base/src/index.ts:236:5)
  name: 'InternalOAuthError',
  message: 'Failed to obtain access token',
  oauthError: { Error: write EPROTO 139876245374848:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:797:
    at _errnoException (util.js:1031:13)
    at WriteWrap.afterWrite (net.js:873:14) errno: 'EPROTO', code: 'EPROTO', syscall: 'write' } }
```

using 
    "https-proxy-agent": "^4.0.0",

**Comment by TooTallNate** [comment]
This module has gone through a large refactor and modernization. I am closing this issue as a bit of house cleaning. If you feel that this issue still exists in the latest release, feel free to open a new issue.
